# -*- coding: utf-8 -*-


"""
Component Mesh2PointMechanicalMapping

.. autofunction:: Mesh2PointMechanicalMapping

Indices and tables
******************

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`
"""

        
def Mesh2PointMechanicalMapping(attachedTo , **kwargs):
    """Mechanical mapping between a set of mesh primitives (point, edge, triangle...) and a set of points generated by Mesh2PointTopologicalMapping


    Args:


    """
    return attachedTo.createObject("Mesh2PointMechanicalMapping" , **kwargs)
