# -*- coding: utf-8 -*-


"""
Component SimpleTesselatedTetraMechanicalMapping

.. autofunction:: SimpleTesselatedTetraMechanicalMapping

Indices and tables
******************

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`
"""

        
def SimpleTesselatedTetraMechanicalMapping(attachedTo , **kwargs):
    """Mechanical mapping between two TetrahedronSetTopologies generated by SimpleTesselatedTetraTopologicalMapping


    Args:


    """
    return attachedTo.createObject("SimpleTesselatedTetraMechanicalMapping" , **kwargs)
